[binary]
path = "/Users/mark.verbeek/Data/Projects/RISC-V-Game-Ready-Emulator/Programs/File/cmake-build-debug-rv32i/File"

[storage]
path = "/Users/mark.verbeek/Data/Projects/RISC-V-Game-Ready-Emulator/rv32_rootfs/File"

[ram]
ram_origin = 0x00000000
ram_size_mb = 32
stack_margin_mb = 2

[framebuffer]
width = 320
height = 200
format = "ARGB"

[debug]
enabled = true
perf_monitor = false
fps = 60

[[debug.breakpoint]]
address = "0x00001234"

[[debug.breakpoint]]
file = "main.c"
line = 42

[init]
randomize_registers = true
randomize_ram = true
zero_bss = true