[binary]
path = "/Users/mark.verbeek/Data/Projects/RISC-V-Game-Ready-Emulator/Programs/File/cmake-build-debug-rv32i/File"

[storage]
path = "/Users/mark.verbeek/Data/Projects/RISC-V-Game-Ready-Emulator/rv32_rootfs/File"

[ram]
ram_origin = 0x00000000
ram_size_mb = 32
stack_margin_mb = 2

[framebuffer]
width = 320
height = 200
format = "ARGB"

[debug]
enabled = false
perf_monitor = false
fps = 35

# [[debug.breakpoint]]
# address = 0x24

[[debug.breakpoint]]
file = "/Users/mark.verbeek/Data/Projects/RISC-V-Game-Ready-Emulator/Programs/File/src/main.c"
line = 612

[init]
randomize_registers = true
randomize_ram = true
zero_bss = true