[binary]
path = "//Users/mark.verbeek/Data/Projects/RISC-V-Game-Ready-Emulator/Programs/RV32DOOM/cmake-build-release-rv32i/RV32DOOM"

[storage]
path = "/Users/mark.verbeek/Data/Projects/RISC-V-Game-Ready-Emulator/rv32_rootfs/DOOM"

[ram]
ram_origin = 0x00000000
ram_size_mb = 32
stack_margin_mb = 2

[framebuffer]
width = 320
height = 200
format = "ARGB"

[debug]
enabled = false

[init]
randomize_registers = true
randomize_ram = true
zero_bss = true